# image is sourced from /static/images/staff/
# desc will be created as a regular text area
# questions will be shown as <strong>question</strong><br>answer
# HTML is preserved

- position: General Manager #GOOD
  email: gm@wcpr.org
  name: Dan Korzen
  image: TESTING.jpg  #kalani_pigao_2019.jpg
  questions:
    Major: Electrical Engineering / Music & Technology Minor
    Hometown: Plantation, FL
    Favorite Artist That I Discovered While Watching A Cartoon Show: Mike Krol
    Best Band Named After Household Appliance: Washer
  description: Yeet


#- position: General Manager #GOOD
#  email: gm@wcpr.org
#  name: Dylan DiGeronimo
#  image: dylan_digeronimo_2019.jpg
#  questions:
#    Major: Computer Science
#    Hometown: Budd Lake, NJ
#    Five Acts You Can't Go On Listening Without: Against Me!, Bon Iver, King Gizzard and the Lizard Wizard, Haruomi Hosono, Mac DeMarco
#    Other Activities: Drinking LaCroix, uploading his conisciousness onto the cloud in order to manifest himself as an all-powerful artificial intelligence, playing guitar 

- position: Programming Manager
  email: programming@wcpr.org
  name: Nicole Naber
  image: nicole_naber_2020.jpg
  questions:
    Major: Mechanical Engineering
    Hometown: Savanna, GA
    My Sources of Happiness: Music, Sitcoms, and Rick and Morty

- position: Business Manager #GOOD
  email: business@wcpr.org
  name: Trent Reichenbach
  image: trent_reichenbach_2020.jpg
  questions:
    Major: Engineer - Undecided
    Hometown: Doylestown, PA
    Fuel Source: Safeway Wild Cherry Clear Splash

#- position: Treasurer and System Administrator #GOOD
#  email: treasurer@wcpr.org
#  name: Kirsten Meidlinger
#  image: kirsten_meidlinger_2019.jpg
#  questions:
#    Major: Computer Science
#    Hometown: South Brunswick, NJ
#    Blurb: I’ve marched drum corps for 2 seasons and I have 3 pet dogs and 6 pet cats at home. 
#  description: I spent all these hours building shelves and this is what I get

#- position: Consultant To The Programming Manager
#  email: programming@wcpr.org
#  name: Tom Bloxam
#  image: tom_bloxam_2019.jpg
#  questions:
#    Major: Music & Technology
#    Hometown: Surrey, UK
#    Loves: Caribou, R.E.M.
#    Has ever picked the vegetarian option on an airplane?: "No"

- position: Publicity Manager #GOOD?
  email: publicity@wcpr.org
  name: Chloe Brenna
  image: chloe_brenna_2021.jpg
  questions:
    Major: Engineering Management
    Hometown: Point Pleasant, NJ
    Fun Fact: My dog went viral on Twitter!
  description: Greetings loved ones B-) 

- position: Webmaster
  email: webmaster@wcpr.org
  name: Kat Ryan
  image: kat_ryan_2021.JPG
  questions:
    Major: Music & Technology
    Hometown: Merrick, NY
    Least favorite nickname given: Katthew
  description: I updated this page, you're welcome!
  
- position: Historian
  email: historian@wcpr.org
  name: Emily McCormick
  image: emily_mccormick_2021.jpg
  questions:
    Major: Biomedical Engineering
    Hometown: Langhorne, PA
    Fun fact: I'm terrified of birds!

- position: Station Engineer ###issue here
  email: engineer@wcpr.org
  name: Kira Mahoney
  image: kira_mahoney_2021.JPG
  questions:
    Major: Music & Technology
    Hometown: Cherry Hill, NJ
    Favorite Least Physical Physical Activities: Scuba diving, skiing, napping

- position: Office Manager and System Administrator #GOOD
  email: office@wcpr.org
  name: Jason Li
  image: jason_li_2021.jpg
  questions:
    Major: Computer Engineering
    Hometown: Denville, NJ
    Underrated Acts: Ben Folds, Classifyde, Fountains of Wayne, Sara Bareilles, They Might Be Giants
    Streets Ahead: Community
  description: Professional Worry Rock

#- position: Record Librarian
#  email: office@wcpr.org
#  name: Antony Cruz
#  image: tony_cruz_2018.png
#  questions:
#    Hometown: Jersey City, NJ
#    Major: Civil Engineering
#    Four Acts You Can't Go On Listening Without: J Dilla, KAYTRANADA, System of a Down, Miles Davis, Ahmad Jamal
#    Hobbies: Beat Making, Record Collection, Lifting, Tony Hawk's Pro Skater, Boxing

#- position: Alumni Liaison #GOOD
#  email: waa@wcpr.org
#  name: Kit Touch-Phong
#  image: kit_touch_pong_2019.jpg
#  questions:
#    Major: Visual Arts & Technology
#    Hometown: Bangkok, TH
#    Top 3 Brad Pitts: Troy, Once Upon a Time in Hollywood, Inglorious Basterds