# image is sourced from /static/images/staff/
# desc will be created as a regular text area
# questions will be shown as <strong>question</strong><br>answer
# HTML is preserved

#- position: General Manager
#  email: gm@wcpr.org
#  name: Emma Murphy
#  image: emma_murphy_2017.jpg
#  questions:
#    Hometown: Brielle, NJ
#    Major: Business & Technology
#    Bands: Blondie, The Cure, SZA, Liz Phair, Joe Jackson
#    Activities: bass, drums, acrylics, oils, movies

#- position: Programming Manager
#  email: programming@wcpr.org
#  name: Dylan DiGeronimo
#  image: dylan_digeronimo_2019.jpg
#  questions:
#    Major: Computer Science
#    Hometown: Budd Lake, NJ
#    Five Acts You Can't Go On Listening Without: Against Me!, Kanye West, King Gizzard and the Lizard Wizard, Haruomi Hosono, Mac DeMarco
#    Other Activities: Drinking LaCroix, uploading his conisciousness onto the cloud in order to manifest himself as an all-powerful artificial intelligence, playing guitar 

- position: General Manager
  email: gm@wcpr.org
  name: Dylan DiGeronimo
  image: dylan_digeronimo_2019.jpg
  questions:
    Major: Computer Science
    Hometown: Budd Lake, NJ
    Five Acts You Can't Go On Listening Without: Against Me!, Kanye West, King Gizzard and the Lizard Wizard, Haruomi Hosono, Mac DeMarco
    Other Activities: Drinking LaCroix, uploading his conisciousness onto the cloud in order to manifest himself as an all-powerful artificial intelligence, playing guitar 
    
- position: Assistant Programming Manager
  email: programming@wcpr.org
  name: Noah Grande
  image: noah_grande_2017.jpg
  description: Noah enjoys long walks on the beach, making beats, sarcasm, and overthrowing the establishment.
  questions:
    Major: Music & Technology
    Hometown: Montclair, NJ
    Favorite Movie: "Speed 2: Cruise Control"

- position: Business Manager
  email: business@wcpr.org
  name: Dante Monteleone
  image: dante_monteleone_2018.jpg 
  questions:
    Hometown: Ocean City, New Jersey
    Major: Finance
    5 acts you can’t go on listening without: Yes, Nils Frahm, Randy Newman, Frank Ocean, Alvvays
    Other Activities: Counting money, ignoring Slack notifications, and drinking the far superior seltzer beverage, Schweppes

- position: Webmaster
  email: webmaster@stevens.edu
  name: Kalani Pigao
  image: kalani_pigao_2019.jpg
  questions:
    Major: Electrical Engineering / Music & Technology Minor
    Hometown: Plantation, FL
    Favorite Strokes Ripoff: No Buses
  description: Yeet
  
- position: Historian
  email: historian@wcpr.org
  name: Laina Emmons
  image: laina_emmons_2019.jpg
  questions:
    Major: Political Science
    Hometown: Lambertville, NJ
    Method Of Liquid Consumption: Mason Jar (exclusively)

- position: Station Engineer
  email: engineer@wcpr.org
  name: Tom Bloxam
  image: tom_bloxam_2018.jpg
  questions:
    Major: Music & Technology
    Hometown: Lehigh, PA & London, England
    Six Acts You Can't Go On Listening Without: Caribou, Daft Punk, Flume, War On Drugs, Mumford and Sons, Elvis Presley
    Favourite Movie: Fight Club
    Unknown Unguilty Pleasure: ABBA's Greatest Hits

- position: Office Manager
  email: office@wcpr.org
  name: Riley Rosa
  image: riley_rosa_2018.jpg
  description: THE UNDISPUTED HEAVYWEIGHT CHAMPION OF THE WORLD
  questions:
    Major: Visual Arts & Technology
    Four Acts You Can't Go On Listening Without: sway beverly, josh from the island, carbe nola, shrine 

- position: Record Librarian
  email: office@wcpr.org
  name: Antony Cruz
  image: tony_cruz_2018.png
  questions:
    Hometown: Jersey City, NJ
    Major: Civil Engineering
    Four Acts You Can't Go On Listening Without: J Dilla, KAYTRANADA, System of a Down, Miles Davis, Ahmad Jamal
    Hobbies: Beat Making, Record Collection, Lifting, Tony Hawk's Pro Skater, Boxing


- position: Alumni Liaison
  email: waa@wcpr.org
  name: Tori Davis
  image: tori_davis_2018.jpg
  questions:
    Major: Mechanical Engineering
    Hometown: Audubon, NJ
    Five Acts You Can't Go On Listening Without: Vundabar, The Promise Ring, Joy Again, (Sandy) Alex G, Crumb
    Hobbies: Bringing fresh pressed juice to mobile units, complaining about anything remotely irritating


- position: System Administrator
  email: sysadmin@wcpr.org
  name: Kirsten Meidlinger
  image: kirsten_roach_2018.jpg
  questions:
    Major: Computer Science
    Hometown: South Brunswick, NJ
    Blurb: I’ve marched drum corps for 2 seasons and I have 3 pet dogs and 6 pet cats at home. 