# image is sourced from /static/images/staff/
# desc will be created as a regular text area
# questions will be shown as <strong>question</strong><br>answer
# HTML is preserved

- position: General Manager #GOOD
  email: gm@wcpr.org
  name: Laina Emmons
  image: laina_emmons_2019.jpg
  questions:
    Major: Political Science
    Hometown: Lambertville, NJ
    Method Of Liquid Consumption: Mason Jar (exclusively)

#- position: General Manager #GOOD
#  email: gm@wcpr.org
#  name: Dylan DiGeronimo
#  image: dylan_digeronimo_2019.jpg
#  questions:
#    Major: Computer Science
#    Hometown: Budd Lake, NJ
#    Five Acts You Can't Go On Listening Without: Against Me!, Bon Iver, King Gizzard and the Lizard Wizard, Haruomi Hosono, Mac DeMarco
#    Other Activities: Drinking LaCroix, uploading his conisciousness onto the cloud in order to manifest himself as an all-powerful artificial intelligence, playing guitar 

- position: Programming Manager
  email: programming@wcpr.org
  name: August Leyda
  image: august_leyda_2019.jpg
  questions:
    Major: Music& Technology
    Hometown: Hudson, WI
    5 Acts You Can't Go On Listening Without: Carly Rae Jepsen, Clarence Clarity, Danny L Harle, Kendrick Lamar, They Might Be Giants
    God-Given Greatest Genre: Bubblegum Bass

- position: Treasurer and System Administrator #GOOD
  email: treasurer@wcpr.org
  name: Kirsten Meidlinger
  image: kirsten_meidlinger_2019.jpg
  questions:
    Major: Computer Science
    Hometown: South Brunswick, NJ
    Blurb: I’ve marched drum corps for 2 seasons and I have 3 pet dogs and 6 pet cats at home. 
  description: I spent all these hours building shelves and this is what I get

#- position: Consultant To The Programming Manager
#  email: programming@wcpr.org
#  name: Tom Bloxam
#  image: tom_bloxam_2019.jpg
#  questions:
#    Major: Music & Technology
#    Hometown: Surrey, UK
#    Loves: Caribou, R.E.M.
#    Has ever picked the vegetarian option on an airplane?: "No"

- position: Publicity Manager #GOOD?
  email: info@wcpr.org
  name: Nicole Naber
  image: nicole_naber_2020.jpg
  questions:
    Major: Mechanical Engineering
    Hometown: Savanna, GA
    My Sources Of Happines: Music, Sitcoms, and Rick And Morty

- position: Webmaster #GOOD
  email: webmaster@wcpr.org
  name: Kalani Pigao
  image: kalani_pigao_2019.jpg
  questions:
    Major: Electrical Engineering / Music & Technology Minor
    Hometown: Plantation, FL
    Favorite Artist That I Discovered While Watching A Cartoon Show: Mike Krol
    Best Stevens Band: Exit 114
  description: Yeet
  
- position: Historian #GOOD
  email: historian@wcpr.org
  name: Madeira Gallagher
  image: madeira_gallagher_2020.jpg
  questions:
    Major: Music Tech
    Hometown: Marlboro, NJ
  description: I'm named after and island!

- position: Station Engineer
  email: engineer@wcpr.org
  name: Jack Kostelnik
  image: jack_kostelnik_2019.jpg
  questions:
    Major: Music and Technology
    Hometown: North Yarmouth, Maine
    Blurb: I love exploring music from outside the United States and learning about other musical cultures. I run a show on WCPR called “Chicken Are People Too” where I play outsider and international music.

- position: Office Manager #GOOD
  email: office@wcpr.org
  name: Trent Reichenbach
  image: trent_reichenbach_2020.jpg
  questions:
    Major: Engineer - Undecided
    Hometown: Doylestown, PA
    Fuel Source: Safeway Wild Cherry Clear Splash

#- position: Record Librarian
#  email: office@wcpr.org
#  name: Antony Cruz
#  image: tony_cruz_2018.png
#  questions:
#    Hometown: Jersey City, NJ
#    Major: Civil Engineering
#    Four Acts You Can't Go On Listening Without: J Dilla, KAYTRANADA, System of a Down, Miles Davis, Ahmad Jamal
#    Hobbies: Beat Making, Record Collection, Lifting, Tony Hawk's Pro Skater, Boxing

#- position: Alumni Liaison #GOOD
#  email: waa@wcpr.org
#  name: Kit Touch-Phong
#  image: kit_touch_pong_2019.jpg
#  questions:
#    Major: Visual Arts & Technology
#    Hometown: Bangkok, TH
#    Top 3 Brad Pitts: Troy, Once Upon a Time in Hollywood, Inglorious Basterds